POST http://localhost:3000/users
Content-Type: application/json


{
    "firstName":"Mark",
    "lastName": "Doe",
    "email": "mark2@ndoes.com",
    "password":"Password123!"
}

POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImVtYWlsIjoibWFya0BuZG9lcy5jb20iLCJpYXQiOjE3NjE1OTk4NzksImV4cCI6MTc2MTYwMzQ3OSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.GSsF1wx00I15sVYYUQpCqBsQ0JloCZJkuzN7yrJoFhY

{
    "users":[
        {
            "firstName":"Mark",
            "lastName": "Doe",
            "email": "mark@ndoes.com",
            "password":"Password123!"
        },
         {
            "firstName":"Poe",
            "lastName": "Doe",
            "email": "poe@ndoes.com",
            "password":"Password123!"
        }
    ]

}